#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

	int counter;
	bool inLine = SensorValue(lightSensor) < 45;

	while(true)                           // Infinite loop
	{


		if(SensorValue(lightSensor) < 45)  	// If the Light Sensor reads a value less than 45:
		{
			motor[rightWheel] = 20;             	// Motor B is run at a 60 power level.
			motor[leftWheel] = 10;               // Motor C is run at a 20 power level.
		}
		else                               	// If the Light Sensor reads a value greater than or equal to 45:
		{
			motor[rightWheel] = 10;               // Motor B is run at a 20 power level.
			motor[leftWheel] = 20;               // Motor C is run at a 60 power level.
		}
	}
}
